apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx-gateway-class
spec:
  controllerName: gateway.nginx.org/nginx-gateway
---
# Note: The controllerName depends on your Gateway implementation
# For NGINX Gateway Fabric: gateway.nginx.org/nginx-gateway
# For Kong: konghq.com/kong-ingress-controller
# For Istio: istio.io/gateway-controller

