apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kubernetes resources to be managed by Kustomize
resources:
  - nginx-depl.yaml
  - nginx-service.yaml
  - nginx-ingress.yaml

# Customizations to be applied
commonLabels:
  company: Adorsys
