apiVersion: v1
kind: Pod # Object Type
metadata:
  name: nginx # Object Name
  labels:
    app: nginx
  annotations:
    description: "This is a simple nginx pod"
spec: # Object Specification
  containers:
  - name: nginx # Container Name
    image: nginx:1.14.2 # Container Image
    ports: # Container Ports to expose
    - containerPort: 80 # Container Port to expose
    resources: # Container Resources
      requests: # Container Resources Requests
        memory: "128Mi" # Container Memory Request
        cpu: "100m" # Container CPU Request
      limits: # Container Resources Limits
        memory: "256Mi" # Container Memory Limit
        cpu: "200m" # Container CPU Limit
    # env: # Container Environment Variables
    #   - name: NGINX_HOST # Container Environment Variable Name
    #     value: "localhost" # Container Environment Variable Value
