apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh-config-layer.fullname" . }}
  labels:
    {{- include "wazuh-config-layer.labels" . | nindent 4 }}
data:
  {{ .Values.config.snippetFileName }}: |
    {{- if .Values.config.extra }}
    {{ .Values.config.extra | trim | nindent 4 }}
    {{- else }}
    <!-- No custom overrides supplied -->
    {{- end }}

