apiVersion: v2
name: bjws-app
version: 0.1.0
description: A sample application Helm chart using bjw-s common library
type: application
keywords:
  - bjw-s
  - common-library
  - app
  - helm
home: https://github.com/bjw-s-labs/helm-charts
sources:
  - https://github.com/bjw-s-labs/helm-charts
maintainers:
  - name: Your Name
    email: your@email.com
dependencies:
  - name: app-template
    version: 4.1.2
    repository: https://bjw-s-labs.github.io/helm-charts